version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_URL: postgresql+psycopg://admin:123@postgres:5432/dnd_db
    volumes:
      - ..:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dnd_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: